#include "noom.h"
#include "lexer.h"

typedef enum noomP_NodeType {
	NOOMP_NODE_PROGRAM,

	NOOMP_NODE_VARNAME,

	NOOMP_NODE_LOCALDECLARATION,
	NOOMP_NODE_IFSTATEMENT,
	NOOMP_NODE_WHILELOOP,
	NOOMP_NODE_FORLOOP,
	NOOMP_NODE_FORLOOPIN,
	NOOMP_NODE_REPEAT,
	NOOMP_NODE_BLOCK,
	NOOMP_NODE_DOBLOCK, // maybe just use BLOCK for this?

	NOOMP_NODE_ATTRIBUTE,

	NOOMP_NODE_BREAK,

	NOOMP_NODE_VARIABLE,
	NOOMP_NODE_NUMBERLITERAL,
	NOOMP_NODE_BOOLEANLITERAL,
	NOOMP_NODE_NILLITERAL,
	NOOMP_NODE_STRINGLITERAL,

	NOOMP_NODE_VARARGLITERAL,

	NOOMP_NODE_TABLELITERAL,
	NOOMP_NODE_TABLEENTRY,

	NOOMP_NODE_UNARYOPERATOR,
	NOOMP_NODE_BINARYOPERATOR,

	NOOMP_NODE_GETFIELD,
	NOOMP_NODE_INDEX,
	NOOMP_NODE_CALL,
	NOOMP_NODE_METHODCALL,

	NOOMP_NODE_STRINGCALL,
	NOOMP_NODE_TABLECALL,

	NOOMP_NODE_STRINGMETHODCALL,
	NOOMP_NODE_TABLEMETHODCALL,

	NOOMP_NODE_LAMBDAFUNCTIONLITERAL,
	NOOMP_NODE_FUNCTIONDECLARATION,
	NOOMP_NODE_LOCALFUNCTIONDECLARATION,
	NOOMP_NODE_FUNCTIONPARAMETERS,
	NOOMP_NODE_FUNCTIONNAME,

	NOOMP_NODE_RETURN,

	NOOMP_NODE_GOTO,
	NOOMP_NODE_LABEL,

	NOOMP_NODE_FIELDNAME,
	NOOMP_NODE_METHODNAME, // only used in function decl as of right now.

	NOOMP_NODE_VARARG,

	NOOMP_NODE_PARENTHESIZED,

	NOOMP_NODE_ASSIGNMENT,
	NOOMP_NODE_ASSIGNPLACE,

	NOOMP_NODE_NCOUNT,
} noomP_NodeType;

typedef enum noomP_Error {
	NOOMP_ERROR_NONE = 0,
	NOOMP_ERROR_OOM,

	NOOMP_ERROR_EXPECTED_LCURLY, // table start
	NOOMP_ERROR_EXPECTED_RCURLY, // table end
	NOOMP_ERROR_EXPECTED_RBRACKET_AFTER_KEY,
	NOOMP_ERROR_EXPECTED_EQUALS_AFTER_KEY,

	NOOMP_ERROR_EXPECTED_FIELD_IDENTIFIER,
	NOOMP_ERROR_EXPECTED_METHOD_CALL,
	NOOMP_ERROR_EXPECTED_RBRACKET_AFTER_INDEX,

	NOOMP_ERROR_EXPECTED_RPAREN_AFTER_EXPRESSION,

	NOOMP_ERROR_EXPECTED_LPAREN_FOR_PARAMETERS,
	NOOMP_ERROR_EXPECTED_RPAREN_FOR_PARAMETERS,

	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_LOCAL_FUNCTION,
	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_FUNCTION,
	NOOMP_ERROR_EXPECTED_END_AFTER_LOCAL_FUNCTION,
	NOOMP_ERROR_EXPECTED_END_AFTER_FUNCTION,

	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_LOCAL,

	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_LANGLE,
	NOOMP_ERROR_EXPECTED_RANGLE_TO_CLOSE_ATTRIBUTE,

	NOOMP_ERROR_EXPECTED_THEN_AFTER_EXPRESSION,
	NOOMP_ERROR_EXPECTED_ELSE_ELSEIF_OR_END,
	NOOMP_ERROR_EXPECTED_END_AFTER_IF,
	NOOMP_ERROR_EXPECTED_DO_AFTER_EXPRESSION,
	NOOMP_ERROR_EXPECTED_END_AFTER_WHILE,
	NOOMP_ERROR_EXPECTED_END_AFTER_FOR,
	NOOMP_ERROR_EXPECTED_END_AFTER_DO,
	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_FOR,
	NOOMP_ERROR_EXPECTED_VARIABLE_AFTER_COMMA_IN_FOR,
	NOOMP_ERROR_EXPECTED_IN,
	NOOMP_ERROR_EXPECTED_UNTIL,

	NOOMP_ERROR_EXPECTED_IDENTIFIER_AFTER_GOTO,
	NOOMP_ERROR_EXPECTED_COLONCOLON,

	NOOMP_ERROR_INVALID_STATEMENT,

	NOOMP_ERROR_EXPECTED_ASSIGNABLE,
	NOOMP_ERROR_NOT_ASSIGNABLE,
	NOOMP_ERROR_EXPECTED_COMMA_OR_EQUAL_IN_ASSIGNMENT,
	NOOMP_ERROR_EXPRESSION_NOT_STATEMENT,

	NOOMP_ERROR_FAKEATTRIBUTE,
	NOOMP_ERROR_RETURN_NOT_END,
	NOOMP_ERROR_FOR_WRONG_AMOUNT,

	NOOMP_ERROR_LEXER = 1 << 31, // bitwise or's with the lexer error number
} noomP_Error;

typedef struct noomP_Node {
	noomP_NodeType type;

	noom_uint_t source_offset;

	noom_uint_t subnodec;
	noom_uint_t subnode_cap;
	struct noomP_Node** subnodes;

	struct noomP_Node* previous_node;
} noomP_Node;

typedef struct noomP_Parser { // todo: track location in code with line/column?
	noom_LuaVersion version;

	const char* code;
	const char* filename;
	noom_uint_t last_token_offset;
	noom_uint_t last_token_length;

	noom_uint_t lex_offset;

	noom_uint_t error_state;

	noomP_Node* last_node;
} noomP_Parser;

const char* noomP_formatNodeType(noomP_NodeType node_type);

int noomP_peek(noomP_Parser* parser, noomL_Token* token);
void noomP_skip(noomP_Parser* parser, noomL_Token* token);

noomP_Node* noomP_allocNode(noomP_Parser* parser);

noomP_Node* noomP_parseFunctionParameters(noomP_Parser* parser);
noomP_Node* noomP_parseBlock(noomP_Parser* parser);

noomP_Node* noomP_parseExpression(noomP_Parser* parser);
noomP_Node* noomP_parseStatement(noomP_Parser* parser);

int noomP_parse(const char* code, const char* filename, noom_LuaVersion version, noomP_Node** outpointer, noomP_Parser* parser);

int noomP_initParser(noomP_Parser* parser, const char* code, const char* filename, noom_LuaVersion version);
